### PR TITLE
Attempt to fix python 3.9 windows build

### PR DESCRIPTION
**Pull request by adament**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adament** [comment]
But it worked.

**Comment by matthewgilbert** [comment]
Okay great, thanks @adament. It seems like most of the changes are related to automated building with the exception of the changes to `recipe/bld.bat`. My impression based on limited understanding is that these files are usually only changed via pushes from the bot which disseminates upstream build infrastructure changes. Is it fine to incorporate these changes directly here or will they get clobbered next time the bot opens a PR?

**Comment by adament** [comment]
Oh yes my only change was to the single line in bld.bat file but I branched from the bots pull request because I needed the python 3.9 pipelines to test my change. Unfortunately I could not push directly to the bots branch (I guess because I am not a mantainer), so I had to open a separate pull request. So I think everything should be fine even as the bots makes changes in the future.

**Comment by matthewgilbert** [comment]
Okay sounds good, in that case I will merge in. Thanks for the fix!

**Pull request merged**
