### PR TITLE
V3.23.1

### PR DESCRIPTION
**Pull request by adament**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adament** [comment]
@conda-forge-admin, please rerender

**Comment by adament** [comment]
@conda-forge-admin, please rerender

**Comment by adament** [comment]
@conda-forge-admin, please rerender

**Comment by adament** [comment]
@conda-forge-admin, please rerender

**Comment by adament** [comment]
I finally got the new version of blpapi to build also on MacOS X. Unfortunately I had to disable building the package for OS X on x86_64 since the binary blpapi C++ library seems to build against MacOS X 12.0 at least I get the error:
```
import: 'blpapi'
Traceback (most recent call last):
  File "/Users/runner/miniforge3/conda-bld/blpapi_1702301589721/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/blpapi/__init__.py", line 27, in <module>
    from .internals import CorrelationId
  File "/Users/runner/miniforge3/conda-bld/blpapi_1702301589721/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/blpapi/internals.py", line 37, in <module>
    from . import _internals
ImportError: dlopen(/Users/runner/miniforge3/conda-bld/blpapi_1702301589721/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/blpapi/_internals.cpython-311-darwin.so, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/runner/miniforge3/conda-bld/blpapi_1702301589721/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/blpapi/../../../libblpapi3_64.so (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/runner/miniforge3/conda-bld/blpapi_1702301589721/test_tmp/run_test.py", line 2, in <module>
    import blpapi
  File "/Users/runner/miniforge3/conda-bld/blpapi_1702301589721/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/blpapi/__init__.py", line 33, in <module>
    raise debug_load_error(error)
ImportError: dlopen(/Users/runner/miniforge3/conda-bld/blpapi_1702301589721/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/blpapi/_versionhelper.cpython-311-darwin.so, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/runner/miniforge3/conda-bld/blpapi_1702301589721/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.11/site-packages/blpapi/../../../libblpapi3_64.so (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib


Could not open the C++ SDK library.

Download and install the latest C++ SDK from:

    http://www.bloomberg.com/professional/api-library

If the C++ SDK is already installed, please ensure that the path to the library
was added to DYLD_LIBRARY_PATH before entering the interpreter.
```
Unfortunately updating MACOSX_DEPLOYMENT_TARGET to 12.0 fails for x86_64 with the error:
```
Mamba failed to solve:
 - libcxx >=16.0.6
 - python_abi 3.10.* *_cp310
 - python >=3.10,<3.11.0a0
 - __osx >=10.9
 - __osx >=12.0

with channels:

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested __osx >=12.0
- 
```
I am a complete newbie to MacOS X and the conda-forge build infrastructure around it, but I think this is because the OSX VM Image that conda-forge uses to build on OS X is an [OS X version 11 image](https://conda-forge.org/docs/user/announcements.html#azure-osx-vm-image-bumped-to-version-11).

**Comment by adament** [comment]
@matthewgilbert is it okay with you if I add myself to the maintainers list?

**Comment by matthewgilbert** [comment]
Yup that would be great!

**Comment by blabalme** [comment]
@conda-forge-admin, please ping team  Is it possible to validate this MR?

**Comment by matthewgilbert** [comment]
Sorry this slipped my radar, @adament is this good to merge?

**Comment by adament** [comment]
Yes this should be good to go, the only downside is that I was unable to get it to build on Mac OS X x86_64 since conda-forge did not have a new enough deployment target.

**Comment by adament** [comment]
@conda-forge-admin please rerender

**Comment by adament** [comment]
I will take a look at fixing the linter errors.

**Comment by adament** [comment]
@conda-forge-admin please rerender

**Comment by adament** [comment]
@matthewgilbert It should be ready now, and it even includes osx x86_64. I think if this is merged first, then afterwards we can look at updating to the newest upstream version.

**Pull request merged**
