### PR TITLE
V3.21.0

### PR DESCRIPTION
**Pull request by adament**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

I am sorry for opening multiple pull requests, I had problems rerendering so I tried deleting my fork and reforking.

### CODE REVIEW

**Comment by adament** [comment]
@conda-forge-admin, please rerender

**Comment by adament** [comment]
@conda-forge-admin, please rerender

**Comment by adament** [comment]
@conda-forge/core This package links against a binary only C++ library [from bloomberg](https://bcms.bloomberg.com/BLPAPI-Generic/blpapi_cpp_3.21.0.1-macos.tar.gz) and if I understand the error messages correctly, this library is built for MacOS X 12.0. Hence the package build fails on OS X when we build for 10.9. Bloomberg also provides binary wheels for macos x, which the filename [blpapi-3.21.0-cp39-cp39-macosx_10_9_x86_64.whl](https://bcms.bloomberg.com/pip/simple/blpapi/blpapi-3.21.0-cp39-cp39-macosx_10_9_x86_64.whl) indicates should run on 10.9, but when I try to build the package from the wheel directly on OS X, the import test still gives an error that the bundled libblpapi3_64.so is built for MacOS X 12.0. This leads me to believe that the filename of the wheel is incorrect. Hence I tried building the python module from source on all platforms and bumping the Mac OS X dependency to 12.0. But then the build errors out because the Mac OS X 12.0 SDK is not available from phracker.

Should I drop OS X support on this package or can we build against the 12.0 SDK?

**Comment by ocefpaf** [comment]
> Should I drop OS X support on this package or can we build against the 12.0 SDK?

You can try a different SDK before dropping it:

https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

**Comment by ocefpaf** [comment]
> Thank you, do you mean I should try to bisect the oldest SDK the build will accept, even if the C++ library was built against the 12.0 SDK?

No idea. I never even held a mac on my hands. I'd try the same SDK and, if that doesn't work and the @conda-forge/blpapi team doesn't care about osx, I'd just drop it and open an issue to follow up later when someone with the expertise shows up.

**Comment by adament** [comment]
> No idea. I never even held a mac on my hands. I'd try the same SDK and, if that doesn't work and the @conda-forge/blpapi team doesn't care about osx, I'd just drop it and open an issue to follow up later when someone with the expertise shows up.

Ah thank you, then we are in similar situations with regard to macs.

I just tried with the 11.0 and 11.3 SDKs and they still fail upon import with a missing symbol error and a note about how the C++ library was built against the 12.0 SDK. And let me just reiterate that attempting to build against the 12.0 SDK failed because newer SDKs than 11.3 are not available in the 
phracker/MacOSX-SDKs#44 repository which the conda-forge pipeline infrastructure seems to rely on.

**Pull request closed without merging**
